services:
  bteq2bq:
    build: .
    ports:
      - "8080:8080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
      CLOUDSDK_CONFIG: /gcloud
      VERTEX_LOCATION: ${VERTEX_LOCATION:-us-central1}
      VERTEX_MODEL: ${VERTEX_MODEL:-gemini-1.5-pro}
      GCP_PROJECT: ${GCP_PROJECT:-project-a9be9c09-ee2e-4b2b-817}
    volumes:
      - ${HOME}/.config/gcloud:/gcloud:ro
